title:            Movimento Fermignano
description:      Pagina ufficiale del Movimento 5 Stelle di Fermignano
# put your disqus here
# disqus_shortname:
facebook_appid: 1015027788580485
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
big_logo:         logo-web-cert.jpg # logo right after the menu on homepage
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

# url: http://www.fermignano5stelle.it
url: http://localhost:4000
# url: http://f5s.sbisinger.net

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Chi siamo'
    url: '/chi-siamo/'
  - title: 'Temi'
    url: '/categories'
    type: 'categories'
  - title: 'Contattaci'
    url: '/contattaci/'

# Owner/author information
owner:
  name:           Movimento 5 Stelle Fermignano
  site:           http://www.fermignano5stelle.it
  avatar:         images/logo.png
  bio:            "Il Movimento 5 Stelle di Fermignano è un gruppo di cittadini
      stufi della solita politica che hanno deciso di prendere la situazione in
      mano."
  email:          info@fermignano5stelle.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: #aron_bordin # if no twitter in this config, the twitter follow button will be removed

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: m5sFermignano

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCnkFmD0l-bzIIauwj4CfxKQ"
  - title: "facebook"
    url: "https://www.facebook.com/fermignano5stelle"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
locale:      it_IT
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:slug/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
